global:
    scrape_interval: 15s                            # Как часто собирать метрики

scrape_configs:
  
  - job_name: 'pools-app'
    scheme: https                                   # Указываем протокол HTTPS
    tls_config:
        insecure_skip_verify: true                  # Пропускать проверку сертификата (для локальных тестов)
    static_configs:
      - targets: ['app:8081']                       # Адрес приложения и порт, где висит /metrics
